=== AleksandrinaKovachka/XML/games_category.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT game_catalog (game*)>
<!ELEMENT game (id, name, note?, developer, publisher, type, available_on, data, count_of, still_playing)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT note (#PCDATA)>
    <!ELEMENT developer (name, headquarters, company_info)>
    <!ELEMENT headquarters (city, country, type)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT company_info (number_employees, website, boss)>
    <!ELEMENT number_employees (#PCDATA)>
    <!ELEMENT website (#PCDATA)>
    <!ELEMENT boss (#PCDATA)>
    <!ELEMENT publisher (name, headquarters, company_info)>
    <!ELEMENT available_on (#PCDATA)>
    <!ELEMENT data (day, month, year)>
    <!ELEMENT day (#PCDATA)>
    <!ELEMENT month (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT count_of (#PCDATA)>
    <!ELEMENT still_playing (#PCDATA)>

    <!ATTLIST developer isin CDATA #REQUIRED>
    <!ATTLIST still_playing present (Да|Не) "Да">
    <!ATTLIST publisher isin CDATA #REQUIRED>
    <!ATTLIST available_on platforms CDATA #REQUIRED>
    <!ATTLIST day value CDATA #REQUIRED>
    <!ATTLIST month value CDATA #REQUIRED>
    <!ATTLIST year value CDATA #REQUIRED>
    <!ATTLIST count_of players CDATA #REQUIRED>


























<!ATTLIST region id CDATA #REQUIRED>
<!ATTLIST mountain has (Да|Не) "Да">
<!ATTLIST average_altitude metric_units CDATA #REQUIRED>
<!ATTLIST length metric_units CDATA #REQUIRED>
<!ATTLIST size metric_units CDATA #REQUIRED>
<!ATTLIST percent percentage CDATA #REQUIRED>
<!ATTLIST average_temperature unit CDATA #REQUIRED>

=== AleksandrinaKovachka/XML/valid_file_js.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE game_catalog SYSTEM "games_category.dtd">

<game_catalog>
    <game>
        <id>1</id>
        <name>Игра на тронове: Генезис</name>
        <note>Играта е адаптация на книгата Песен за огън и лед</note>
        <developer isin="FR0000074072">
            <name>Цианид</name>
            <headquarters>
                <city>Париж</city>
                <country>Франция</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>110</number_employees>
                <website>cyanide-studio.com</website>
                <boss>Патрик Плигерсдорфър</boss>
            </company_info>
        </developer>
        <publisher isin="FR0012419307">
            <name>Фокус Хоум</name>
            <headquarters>
                <city>Париж</city>
                <country>Франция</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>162</number_employees>
                <website>focus-home.com</website>
                <boss>Цедрик Лагаригу</boss>
            </company_info>
        </publisher>
        <type>стратегическа</type>
        <available_on platforms="1"/>
        <data>
            <day value="day">28</day>
            <month value="month">09</month>
            <year value="year">2011</year>
        </data>
        <count_of players="1"/>
        <still_playing present="Да"/>
    </game>
</game_catalog>

=== AleksandrinaKovachka/XML/valid_xml_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE game_catalog SYSTEM "games_category.dtd">

<game_catalog>
    <game>
        <id>5</id>
        <name>Фортнайт</name>
        <note>Играчите трябва да убият зомби същества и да защитават обекти с капани и укрепления, които могат да изградят</note>
        <developer isin="US29428L4032">
            <name>Епик Гейм</name>
            <headquarters>
                <city>Кари</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>1000</number_employees>
                <website>epicgames.com</website>
                <boss>Тим Сленъй</boss>
            </company_info>
        </developer>
        <publisher isin="US29428L4032">
            <name>Епик Гейм</name>
            <headquarters>
                <city>Кари</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>1000</number_employees>
                <website>epicgames.com</website>
                <boss>Тим Сленъй</boss>
            </company_info>
        </publisher>
        <type>игра на оцеляване</type>
        <available_on platforms="9"/>
        <data>
            <day value="day">25</day>
            <month value="month">07</month>
            <year value="year">2017</year>
        </data>
        <count_of players="много"/>
        <still_playing present="Да"/>
    </game>
</game_catalog>

=== AleksandrinaKovachka/XML/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE game_catalog SYSTEM "games_category.dtd">

<game_catalog>
    <game>
        <id>4</id>
        <name>Дългът зове: Безкрайната война</name>
        <note>Играта е адаптация на книгата Песен за огън и лед</note>
        <developer isin="US00507V1098">
            <name>Инфинити Лърд</name>
            <headquarters>
                <city>Лоулдлънд Хил</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>444</number_employees>
                <website>www.infinityward.com</website>
                <boss>Грант Колиер</boss>
            </company_info>
        </developer>
        <publisher isin="US00507V109">
            <name>Активижън</name>
            <headquarters>
                <city>Санта Моника</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>9100</number_employees>
                <website>activision.com</website>
                <boss>Давид Грейн</boss>
            </company_info>
        </publisher>
        <type>първи играч стреля</type>
        <available_on platforms="2"/>
        <data>
            <day value="day">04</day>
            <month value="month">11</month>
            <year value="year">2014</year>
        </data>
        <count_of players="много"/>
        <still_playing present="Да"/>
    </game>
</game_catalog>

=== AleksandrinaKovachka/XML/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE game_catalog SYSTEM "games_category.dtd">

<game_catalog>
    <game>
        <id>2</id>
        <name>Чудесата на годините: Магия на сенките</name>
        <note>Магията на сенките е стратегическа видео игра, базирана на стъпки, във фантастична обстановка.</note>
        <developer isin="SE0008294953">
            <name>Триумф Студио</name>
            <headquarters>
                <city>Дефт</city>
                <country>Холандия</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>40</number_employees>
                <website>triumph.net</website>
                <boss>Ленарт Сас</boss>
            </company_info>
        </developer>
        <publisher isin="">
            <name>Гедъринг</name>
            <headquarters>
                <city>Ню Йорк</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>200</number_employees>
                <website>www.godgames.com</website>
                <boss>Мике Лилсън</boss>
            </company_info>
        </publisher>
        <type>стратегическа</type>
        <available_on platforms=""/>
        <data>
            <day value="day">25</day>
            <month value="month">07</month>
            <year value="year">2003</year>
        </data>
        <count_of players="много"/>
        <still_playing present="Не"/>
    </game>
</game_catalog>

=== AleksandrinaKovachka/XML/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE game_catalog SYSTEM "games_category.dtd">

<game_catalog>
    <game>
        <id>3</id>
        <name>Алън Уейк</name>
        <note>Историята проследява най-продавания роман на трилъра Алън Уейк, докато се опитва да разкрие тайната на изчезването на жена си по време на ваканция</note>
        <developer isin="FI4000251897">
            <name>Ремеди</name>
            <headquarters>
                <city>Еспо</city>
                <country>Финландия</country>
                <type>основна компания</type>
            </headquarters>
            <company_info>
                <number_employees>280</number_employees>
                <website>remedygames.com</website>
                <boss>Маркус Майки</boss>
            </company_info>
        </developer>
        <publisher isin="US5949181045">
            <name>ХБокс Майкрософт Студио</name>
            <headquarters>
                <city>Редмонд</city>
                <country>САЩ</country>
                <type>дъщерна компания</type>
            </headquarters>
            <company_info>
                <number_employees>2433</number_employees>
                <website>xbox.com/xbox-game-studios</website>
                <boss>Фил Спенсър</boss>
            </company_info>
        </publisher>
        <type>приключенска</type>
        <available_on platforms="1"/>
        <data>
            <day value="day">14</day>
            <month value="month">05</month>
            <year value="year">2010</year>
        </data>
        <count_of players="1"/>
        <still_playing present="Да"/>
    </game>
</game_catalog>
